### ISSUE TITLE
Can't render genesis block in Polkadot.js explorer

### ISSUE THREAD

**Issue by nazar-pc** [subspace/polkadot-js-apps#14]
Apparently there is something about genesis block that makes Polkadot.js explorer unable to decode it:
```
Unable to retrieve the specified block details. can't access property "asPreRuntime", n[0] is undefined
```

Genesis block is a bit special and might need extra care, but I do think we want to render it properly (happens both with 2022-jan-05 and 2022-mar-09 builds).

**Comment by 1devNdogs** [comment]
Thanks for this check, added validation on the **`extractAuthor`** function. 
If there are no **preRuntimes** logs will skip extraction and render information correctly.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Faries-farm-rpc-b.subspace.network#/explorer/query/0
![image](https://user-images.githubusercontent.com/11360704/162669456-7ca1c8ee-4f69-42b6-b405-f3507f68da89.png)
